version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
  microservice1.api: 
    image: osmant12/microservice1:${version}
    container_name: microservice1-container
    build:
      context: .
      dockerfile: MicroService1.API/Dockerfile
  microservice2.api: 
    image: osmant12/microservice2:${version}
    container_name: microservice2-container
    build:
      context: .
      dockerfile: MicroService2.API/Dockerfile
volumes:
  sqlserver_volume: 